version: '3'

services:
  db:
    image: youdi/mysql-osx
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
    volumes:
      - .:/var/www/project
    ports:
      - "8080:8080"